upload project
stepancar-web-programming/2023-fall-lab-portfolio-suvorov-d.-v. pull request #9
Opened 2023-11-17 09:25 UTC by Erkobrax

Удалил ветку dev, создал новую ветку dev 
Запушил изменения в нее и уже из этой ветки сделал PR в main ( до этого был PR из ветки dev репозитория, который является форком, а не из ветки dev репозитория изначального )

2023-11-22 00:59 UTC, stepancar commented
@Erkobrax , работа очень похожа на вашу работу прошлого года
https://erkobrax.github.io/2022-fall-lab-portfolio-suvorov-denis-vitalevich-1/

Прошу вас всетки потрудиться над лабораторной, сделать что-то новое. Если в прошлом году эта работа была зачтена - могу поставить за нее балл который вы получили в прошлом году.

2023-11-22 01:01 UTC, stepancar requested changes
Copy paste of https://github.com/stepancar-web-programming/2022-fall-lab-portfolio-suvorov-denis-vitalevich/pull/4

2023-11-28 14:37 UTC, Erkobrax commented
@stepancar добавил новые элементы на html страницы, добавил к ним css, написал новые скрипты

2023-12-06 22:53 UTC, stepancar commented on scripts/index.js
> +let slideIndex = 0;
Если открыть ваш сайт и devTools есть возможность читать и писать `slideIndex`. Предлагаю сделать изоляцию

2023-12-06 22:55 UTC, stepancar commented on scripts/index.js
> +  let i;
заметьте, что вы используете этот идентификатор внутри for, тогда следует его там и объявить. Думаю что, eslint со стандартным конфигом смог бы вам тут помочь

2023-12-06 22:56 UTC, stepancar commented on style.css
> +#ttt {
Давайте найдем имя получше?

2023-12-06 22:57 UTC, stepancar commented on scripts/dog.js
> +});
Пожалуйста, отформатируйте код, перед отправкой на ревью

2023-12-06 22:58 UTC, stepancar requested changes
Прошу отформатировать код и добавить eslint / prettier

2023-12-11 15:33 UTC, Erkobrax commented on scripts/dog.js
> +});
исправил

2023-12-11 15:33 UTC, Erkobrax commented on style.css
> +#ttt {
исправил

2023-12-11 15:33 UTC, Erkobrax commented on scripts/index.js
> +  let i;
исправил

2023-12-11 15:33 UTC, Erkobrax commented on scripts/index.js
> +let slideIndex = 0;
исправил

2023-12-11 15:36 UTC, Erkobrax commented
@stepancar исправил все замечания

2024-01-04 04:16 UTC, stepancar commented on style.css
> +#videoContainer{
Пожалуйста, приведите код к единым стандартам. Для этого вы можете мспользовать esling, stylelint, prettier

2024-01-04 04:21 UTC, stepancar commented on scripts/menu.js
> +// eslint-disable-next-line no-restricted-syntax
Если вы следуете гайдлайнам airbnb - то следуйте им если можете - тут нет большой проблемы им следовать. Если они вам не подходят - то не нужно выключать правило точечно - выключите для всего проекта

2024-01-04 04:25 UTC, stepancar commented on scripts/dog.js
> +const dog = document.getElementById('dog');
Обратите внимание, к переменным вашей программы можно обратиться извне. Пожалуйста изолируйте доступ.

2024-01-04 04:25 UTC, stepancar requested changes
Оставил комментарии

2024-01-05 19:39 UTC, Erkobrax commented on scripts/dog.js
> +const dog = document.getElementById('dog');
исправил

2024-01-05 19:39 UTC, Erkobrax commented on scripts/menu.js
> +// eslint-disable-next-line no-restricted-syntax
исправил

2024-01-05 21:11 UTC, Erkobrax commented
@stepancar исправил

2024-01-06 03:46 UTC, stepancar commented on scripts/dog.js
> +  const dog = document.getElementById('dog');
Покажите editorconfig которым вы пользуетесь для форматирования?
Ощущение что форматирование сделано не автоматическими средствами

2024-01-06 03:48 UTC, stepancar commented on scripts/dog.js
> +  const dog = document.getElementById('dog');
по крайней мере, в соседнем файле форматирование другое

2024-01-06 14:30 UTC, Erkobrax commented on scripts/dog.js
> +  const dog = document.getElementById('dog');
А я не знаю, почему автоматически не применилось форматирование к коду
Обычно он подсвечивал это
Примел editorconfig ко всем файлам

2024-01-07 05:58 UTC, stepancar approved these changes
Заметьте что все что мы тут с вами обсудили - это форматирование и оформление. Если бы вы сразу сделали автоматизацию - вы бы не попали в ситуацию в которой у вас на ревью попал код не подготовленный к ревью. Тогда у нас бы с вами была возможность обсудить что-то более значимое. 
Создание ПР и поддержание кода в консистентном виде - это часть работы разработчика. Для того чтобы доставлять до релиза ваши доработки, вам придется писать код в таком виде чтобы другие разработчики вас поняли. врядли вы хотите получать комментарии по форматированию от человека. Наверное вы бы на ревью хотели получить что-то полезное. Я вам рекомендую потрудиться над созданием своего собственного шаблона, где у вас сразу настроен ci, настроены тесты, линтеры, форматирование, линтеры коммитов, чтобы до ревью доходил код которы хотябы проверен автоматикой. Так вы съэкономите огромное количесвто времени себе и ревьюеру.

2024-01-07 06:00 UTC, merged